services:
  logtopus:
    build:
      context: .
      dockerfile: Dockerfile.ingestor
    ports:
      - "${PORT:-8080}:8080"
    environment:
      - PORT=8080
      - AUTH_SECRET=${AUTH_SECRET}
      - ENABLE_FILE_LOGGING=true
      - FILE_LOG_DIR=/app/logs
      - ENABLE_CLICKHOUSE=false
    volumes:
      - app_logs:/app/logs

  query-service:
    build:
      context: .
      dockerfile: Dockerfile.query
    command: ./query-service
    restart: on-failure
    ports:
      - "${QUERY_PORT:-8081}:8081"
    environment:
      - QUERY_PORT=8081
      - SEARCH_DIR=/app/logs
    volumes:
      - app_logs:/app/logs

volumes:
  app_logs:
